name: Automate Pull Request Creation
description: "Creates a pull request from a branch and optionally adds labels and a comment."
author: "owen-6936"
branding:
  icon: "git-pull-request"
  color: "green"

inputs:
  github-token:
    description: "GitHub token for authentication."
    required: true

  branch:
    description: "Source branch for the pull request."
    required: true

  base-branch:
    description: "Target branch for the pull request."
    required: true

  title:
    description: "Title of the pull request."
    required: false
    default: "PR created by automated workflow"

  body:
    description: "Body content of the pull request."
    required: false
    default: "This pull request was automatically created by a workflow."

  labels:
    description: "Comma-separated list of labels to apply."
    required: false
    default: "automated"

  comment-body:
    description: "Optional comment to post after PR creation."
    required: false
    default: ""

outputs:
  pr_number:
    description: "Number of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr_url:
    description: "URL of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      id: create-pr
      shell: bash
      run: |
        set -e

        pr_body_md=$(printf "## 🤖 Automated PR\n\nThis pull request was generated from branch \`%s\`\n\n%s\n\n### Workflow Metadata\n- Triggered by: \`%s\`\n- Commit: \`%s\`\n- Actor: \`%s\`" \
          "${{ inputs.branch }}" \
          "${{ inputs.body }}" \
          "${{ github.workflow }}" \
          "${{ github.sha }}" \
          "${{ github.actor }}")

        pr_url=$(gh pr create \
          --title "${{ inputs.title }}" \
          --body "$pr_body_md" \
          --base "${{ inputs.base-branch }}" \
          --head "${{ inputs.branch }}" \
          --label "${{ inputs.labels }}" \
          --repo "${{ github.repository }}")

        pr_number=$(basename "$pr_url")

        echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
        echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"

        echo "✅ Created PR #$pr_number at $pr_url"
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Add Comment to PR
      if: ${{ inputs.comment-body != '' }}
      shell: bash
      run: |
        gh pr comment "$pr_url" --body "${{ inputs.comment-body }}"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
