name: Automate Pull Request Creation
description: "Automates the creation of pull requests from a branch, including setting the title, body, and base branch."
author: "owen-6936"
branding:
  icon: "git-pull-request"
  color: "green"

inputs:
  github-token:
    description: "The GitHub token to use for creating the pull request."
    required: true
  branch:
    required: true
    description: "The branch from which the pull request is created."
  base-branch:
    description: "The base branch to create the pull request against."
    required: true
  title:
    description: "The title for the new pull request."
    default: "PR created by automated workflow"
    required: false
  body:
    description: "The body content for the new pull request."
    default: "This pull request was automatically created by a workflow."
    required: false

outputs:
  pr_number:
    description: "The number of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr_url:
    description: "The URL of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      id: create-pr
      shell: bash
      run: |
        pr_data=$(gh pr create \
          --title "${{ inputs.title }}" \
          --body "$(printf "## 🤖 Automated PR\n\nThis pull request was generated from branch \`%s\`\n\n%s\n\n### Workflow Metadata\n- Triggered by: \`%s\`\n- Commit: \`%s\`\n- Actor: \`%s\`" \
            "${{ inputs.branch }}" \
            "${{ inputs.body }}" \
            "${{ github.workflow }}" \
            "${{ github.sha }}" \
            "${{ github.actor }}")" \
          --base "${{ inputs.base-branch }}" \
          --head "${{ inputs.branch }}" \
          --json number,url)

        pr_number=$(echo "$pr_data" | jq -r '.number')
        pr_url=$(echo "$pr_data" | jq -r '.url')

        echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
        echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"

        echo "Successfully created pull request #$pr_number at $pr_url"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
