name: Automate Pull Request Creation
description: "Automates the creation of pull requests from a branch, including setting the title, body, and base branch."
author: "owen-6936"
branding:
  icon: "git-pull-request"
  color: "green"

inputs:
  github-token:
    description: "The GitHub token to use for creating the pull request."
    required: true
  branch:
    required: true
    description: "The branch from which the pull request is created."
  base-branch:
    description: "The base branch to create the pull request against."
    required: true
  title:
    description: "The title for the new pull request."
    default: "PR created by automated workflow"
    required: false
  body:
    description: "The body content for the new pull request."
    default: "This pull request was automatically created by a workflow."
    required: false

outputs:
  pr_number:
    description: "The number of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr_url:
    description: "The URL of the created pull request."
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      id: create-pr
      shell: bash
      run: |
        body_template="## 🤖 Automated PR\n\nThis pull request was generated from branch \`${{ inputs.branch }}\`\n\n"

        # Only include the body if it's not an empty string
        if [[ ! -z "${{ inputs.body }}" ]]; then
          body_template+="${{ inputs.body }}\n\n"
        fi

        body_template+="### Workflow Metadata\n- Triggered by: \`${{ github.workflow }}\`\n- Commit: \`${{ github.sha }}\`\n- Actor: \`${{ github.actor }}\`"

        pr_data=$(gh pr create \
          --title "${{ inputs.title }}" \
          --body "$body_template" \
          --base "${{ inputs.base-branch }}" \
          --head "${{ inputs.branch }}")

        pr_number=$(basename "$pr_data")
        pr_url="$pr_data"

        echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
        echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"

        echo "Successfully created pull request #$pr_number at $pr_url"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
