name: Test Automate Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  parse-commit-message:
    runs-on: ubuntu-latest
    outputs:
      head_message: ${{ steps.commit-message-parser.outputs.head_message }}
      body_message: ${{ steps.commit-message-parser.outputs.body_message }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract head and body of commit message
        id: "commit-message-parser"
        shell: bash
        run: |
          full_message="${{ github.event.head_commit.message }}"
          head_message=$(echo "$full_message" | head -n 1)

          if [[ "$full_message" != "$head_message" ]]; then
            body_message=$(echo "$full_message" | tail -n +2)
            
            echo "head_message=$head_message" >> "$GITHUB_OUTPUT"
            echo "body_message<<EOF" >> "$GITHUB_OUTPUT"
            echo "$body_message" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
            
          else
            head_message="$full_message"
            
            echo "head_message=$head_message" >> "$GITHUB_OUTPUT"
            echo "body_message=" >> "$GITHUB_OUTPUT"
          fi

  create-pr:
    runs-on: ubuntu-latest
    needs: [parse-commit-message]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.ref_name}}
          base-branch: main
          title: ${{ needs.parse-commit-message.outputs.head_message }}
          body: ${{ needs.parse-commit-message.outputs.body_message }}
